// ============================================
// ПРЕДУСТАНОВЛЕННЫЕ ПАРАМЕТРЫ ТОВАРОВ
// Конструктор параметров для админки
// ============================================

import { ProductParameter, ParameterGroup } from "./index";

// ===== ГРУППЫ ПАРАМЕТРОВ =====
export const DEFAULT_PARAMETER_GROUPS: ParameterGroup[] = [
  {
    id: "group-main",
    name: "Основные характеристики",
    code: "main",
    order: 1,
    isExpanded: true,
  },
  {
    id: "group-dimensions",
    name: "Размеры и вес",
    code: "dimensions",
    order: 2,
    isExpanded: true,
  },
  {
    id: "group-materials",
    name: "Материалы",
    code: "materials",
    order: 3,
    isExpanded: true,
  },
  {
    id: "group-appearance",
    name: "Внешний вид",
    code: "appearance",
    order: 4,
    isExpanded: false,
  },
  {
    id: "group-comfort",
    name: "Комфорт и эргономика",
    code: "comfort",
    order: 5,
    isExpanded: false,
  },
  {
    id: "group-additional",
    name: "Дополнительно",
    code: "additional",
    order: 6,
    isExpanded: false,
  },
];

// ===== ВСЕ ПАРАМЕТРЫ =====
export const DEFAULT_PARAMETERS: ProductParameter[] = [
  // ========== ОСНОВНЫЕ ==========
  {
    id: "param-chair-type",
    code: "chairType",
    name: "Тип стула",
    type: "select",
    options: [
      { value: "dining", label: "Обеденный" },
      { value: "bar", label: "Барный" },
      { value: "office", label: "Офисный" },
      { value: "gaming", label: "Игровой" },
      { value: "lounge", label: "Лаунж" },
      { value: "folding", label: "Складной" },
      { value: "stool", label: "Табурет" },
      { value: "bench", label: "Банкетка" },
      { value: "kids", label: "Детский" },
    ],
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 1,
    group: "main",
    avitoField: "Тип стула",
  },
  {
    id: "param-product-type",
    code: "productType",
    name: "Вид товара",
    type: "select",
    options: [
      { value: "chair", label: "Стул" },
      { value: "table", label: "Стол" },
      { value: "armchair", label: "Кресло" },
      { value: "sofa", label: "Диван" },
      { value: "bed", label: "Кровать" },
      { value: "storage", label: "Хранение" },
      { value: "lighting", label: "Освещение" },
      { value: "decor", label: "Декор" },
    ],
    required: true,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: true,
    order: 2,
    group: "main",
    avitoField: "Вид товара",
  },
  {
    id: "param-construction",
    code: "construction",
    name: "Конструкция",
    type: "select",
    options: [
      { value: "solid", label: "Цельная" },
      { value: "folding", label: "Складная" },
      { value: "modular", label: "Модульная" },
      { value: "stackable", label: "Штабелируемая" },
      { value: "adjustable", label: "Регулируемая" },
    ],
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 3,
    group: "main",
    avitoField: "Конструкция",
  },
  {
    id: "param-quantity",
    code: "quantity",
    name: "Количество в комплекте",
    type: "number",
    unit: "шт",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: true,
    order: 4,
    group: "main",
    avitoField: "Количество стульев",
  },
  {
    id: "param-max-load",
    code: "maxLoad",
    name: "Максимальная нагрузка",
    type: "number",
    unit: "кг",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 5,
    group: "main",
  },
  {
    id: "param-manufacturer",
    code: "manufacturer",
    name: "Производитель",
    type: "select",
    options: [], // Заполняется динамически
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 6,
    group: "main",
  },
  {
    id: "param-country",
    code: "country",
    name: "Страна производства",
    type: "select",
    options: [
      { value: "russia", label: "Россия" },
      { value: "china", label: "Китай" },
      { value: "italy", label: "Италия" },
      { value: "germany", label: "Германия" },
      { value: "poland", label: "Польша" },
      { value: "turkey", label: "Турция" },
      { value: "belarus", label: "Беларусь" },
    ],
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 7,
    group: "main",
  },

  // ========== РАЗМЕРЫ И ВЕС ==========
  {
    id: "param-width",
    code: "width",
    name: "Ширина",
    type: "number",
    unit: "см",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 1,
    group: "dimensions",
    avitoField: "Ширина (Для Доставки)",
  },
  {
    id: "param-height",
    code: "height",
    name: "Высота",
    type: "number",
    unit: "см",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 2,
    group: "dimensions",
    avitoField: "Высота (Для Доставки)",
  },
  {
    id: "param-depth",
    code: "depth",
    name: "Глубина",
    type: "number",
    unit: "см",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 3,
    group: "dimensions",
    avitoField: "Длина (Для Доставки)",
  },
  {
    id: "param-seat-height",
    code: "seatHeight",
    name: "Высота сиденья",
    type: "number",
    unit: "см",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 4,
    group: "dimensions",
  },
  {
    id: "param-seat-width",
    code: "seatWidth",
    name: "Ширина сиденья",
    type: "number",
    unit: "см",
    required: false,
    filterable: false,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 5,
    group: "dimensions",
  },
  {
    id: "param-seat-depth",
    code: "seatDepth",
    name: "Глубина сиденья",
    type: "number",
    unit: "см",
    required: false,
    filterable: false,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 6,
    group: "dimensions",
  },
  {
    id: "param-weight",
    code: "weight",
    name: "Вес",
    type: "number",
    unit: "кг",
    required: false,
    filterable: false,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 7,
    group: "dimensions",
    avitoField: "Вес (Для Доставки)",
  },
  {
    id: "param-package-weight",
    code: "packageWeight",
    name: "Вес в упаковке",
    type: "number",
    unit: "кг",
    required: false,
    filterable: false,
    comparable: false,
    showInCard: false,
    showInList: false,
    order: 8,
    group: "dimensions",
  },

  // ========== МАТЕРИАЛЫ ==========
  {
    id: "param-frame-material",
    code: "frameMaterial",
    name: "Материал каркаса",
    type: "multiselect",
    options: [
      { value: "metal", label: "Металл" },
      { value: "steel", label: "Сталь" },
      { value: "aluminum", label: "Алюминий" },
      { value: "wood", label: "Дерево" },
      { value: "oak", label: "Дуб" },
      { value: "beech", label: "Бук" },
      { value: "birch", label: "Берёза" },
      { value: "pine", label: "Сосна" },
      { value: "plywood", label: "Фанера" },
      { value: "mdf", label: "МДФ" },
      { value: "chipboard", label: "ДСП" },
      { value: "plastic", label: "Пластик" },
      { value: "rattan", label: "Ротанг" },
    ],
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 1,
    group: "materials",
    avitoField: "Материал основания",
  },
  {
    id: "param-seat-material",
    code: "seatMaterial",
    name: "Материал сиденья",
    type: "multiselect",
    options: [
      { value: "velour", label: "Велюр" },
      { value: "textile", label: "Текстиль" },
      { value: "leather", label: "Натуральная кожа" },
      { value: "eco-leather", label: "Экокожа" },
      { value: "leatherette", label: "Кожзам" },
      { value: "boucle", label: "Букле" },
      { value: "mesh", label: "Сетка" },
      { value: "plastic", label: "Пластик" },
      { value: "wood", label: "Дерево" },
      { value: "rattan", label: "Ротанг" },
      { value: "foam", label: "Поролон (ППУ)" },
    ],
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 2,
    group: "materials",
    avitoField: "Материал сиденья",
  },
  {
    id: "param-back-material",
    code: "backMaterial",
    name: "Материал спинки",
    type: "multiselect",
    options: [
      { value: "velour", label: "Велюр" },
      { value: "textile", label: "Текстиль" },
      { value: "leather", label: "Натуральная кожа" },
      { value: "eco-leather", label: "Экокожа" },
      { value: "mesh", label: "Сетка" },
      { value: "plastic", label: "Пластик" },
      { value: "wood", label: "Дерево" },
    ],
    required: false,
    filterable: false,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 3,
    group: "materials",
  },
  {
    id: "param-tabletop-material",
    code: "tabletopMaterial",
    name: "Материал столешницы",
    type: "select",
    options: [
      { value: "glass", label: "Стекло" },
      { value: "tempered-glass", label: "Закалённое стекло" },
      { value: "wood", label: "Массив дерева" },
      { value: "mdf", label: "МДФ" },
      { value: "chipboard", label: "ЛДСП" },
      { value: "stone", label: "Камень" },
      { value: "marble", label: "Мрамор" },
      { value: "ceramic", label: "Керамика" },
      { value: "hpl", label: "HPL пластик" },
    ],
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 4,
    group: "materials",
  },

  // ========== ВНЕШНИЙ ВИД ==========
  {
    id: "param-color",
    code: "color",
    name: "Цвет",
    type: "color",
    options: [
      { value: "white", label: "Белый", color: "#FFFFFF" },
      { value: "black", label: "Чёрный", color: "#000000" },
      { value: "gray", label: "Серый", color: "#808080" },
      { value: "beige", label: "Бежевый", color: "#F5F5DC" },
      { value: "brown", label: "Коричневый", color: "#8B4513" },
      { value: "blue", label: "Синий", color: "#0000FF" },
      { value: "green", label: "Зелёный", color: "#008000" },
      { value: "red", label: "Красный", color: "#FF0000" },
      { value: "pink", label: "Розовый", color: "#FFC0CB" },
      { value: "yellow", label: "Жёлтый", color: "#FFFF00" },
      { value: "orange", label: "Оранжевый", color: "#FFA500" },
      { value: "purple", label: "Фиолетовый", color: "#800080" },
      { value: "turquoise", label: "Бирюзовый", color: "#40E0D0" },
      { value: "gold", label: "Золотой", color: "#FFD700" },
      { value: "silver", label: "Серебряный", color: "#C0C0C0" },
      { value: "natural", label: "Натуральный", color: "#DEB887" },
    ],
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: true,
    order: 1,
    group: "appearance",
    avitoField: "Основной цвет",
  },
  {
    id: "param-manufacturer-color",
    code: "manufacturerColor",
    name: "Цвет от производителя",
    type: "text",
    required: false,
    filterable: false,
    comparable: false,
    showInCard: true,
    showInList: false,
    order: 2,
    group: "appearance",
    avitoField: "Цвет от производителя",
  },
  {
    id: "param-frame-color",
    code: "frameColor",
    name: "Цвет каркаса",
    type: "select",
    options: [
      { value: "black", label: "Чёрный", color: "#000000" },
      { value: "white", label: "Белый", color: "#FFFFFF" },
      { value: "chrome", label: "Хром", color: "#C0C0C0" },
      { value: "gold", label: "Золото", color: "#FFD700" },
      { value: "bronze", label: "Бронза", color: "#CD7F32" },
      { value: "natural-wood", label: "Натуральное дерево", color: "#DEB887" },
      { value: "dark-wood", label: "Тёмное дерево", color: "#654321" },
    ],
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 3,
    group: "appearance",
  },
  {
    id: "param-style",
    code: "style",
    name: "Стиль",
    type: "multiselect",
    options: [
      { value: "modern", label: "Современный" },
      { value: "classic", label: "Классика" },
      { value: "loft", label: "Лофт" },
      { value: "scandinavian", label: "Скандинавский" },
      { value: "minimalism", label: "Минимализм" },
      { value: "industrial", label: "Индустриальный" },
      { value: "provence", label: "Прованс" },
      { value: "art-deco", label: "Ар-деко" },
      { value: "retro", label: "Ретро" },
      { value: "hi-tech", label: "Хай-тек" },
    ],
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 4,
    group: "appearance",
  },

  // ========== КОМФОРТ И ЭРГОНОМИКА ==========
  {
    id: "param-has-armrests",
    code: "hasArmrests",
    name: "Подлокотники",
    type: "boolean",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 1,
    group: "comfort",
  },
  {
    id: "param-has-headrest",
    code: "hasHeadrest",
    name: "Подголовник",
    type: "boolean",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 2,
    group: "comfort",
  },
  {
    id: "param-is-foldable",
    code: "isFoldable",
    name: "Складной",
    type: "boolean",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 3,
    group: "comfort",
    avitoField: "Складной",
  },
  {
    id: "param-is-rotatable",
    code: "isRotatable",
    name: "Вращается",
    type: "boolean",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 4,
    group: "comfort",
  },
  {
    id: "param-height-adjustable",
    code: "heightAdjustable",
    name: "Регулировка высоты",
    type: "boolean",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 5,
    group: "comfort",
  },
  {
    id: "param-back-adjustable",
    code: "backAdjustable",
    name: "Регулировка спинки",
    type: "boolean",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 6,
    group: "comfort",
  },
  {
    id: "param-has-wheels",
    code: "hasWheels",
    name: "На колёсиках",
    type: "boolean",
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 7,
    group: "comfort",
  },
  {
    id: "param-features",
    code: "features",
    name: "Особенности",
    type: "multiselect",
    options: [
      { value: "soft-seat", label: "Мягкое сиденье" },
      { value: "ergonomic", label: "Эргономичный" },
      { value: "orthopedic", label: "Ортопедический" },
      { value: "anti-claw", label: "Антикоготь" },
      { value: "waterproof", label: "Влагостойкий" },
      { value: "easy-clean", label: "Легко чистить" },
      { value: "uv-resistant", label: "Защита от УФ" },
      { value: "scratch-resistant", label: "Устойчив к царапинам" },
    ],
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 8,
    group: "comfort",
    avitoField: "Что есть у стула",
  },

  // ========== ДОПОЛНИТЕЛЬНО ==========
  {
    id: "param-assembly",
    code: "assembly",
    name: "Сборка",
    type: "select",
    options: [
      { value: "assembled", label: "В сборе" },
      { value: "requires-assembly", label: "Требует сборки" },
      { value: "partial", label: "Частичная сборка" },
    ],
    required: false,
    filterable: true,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 1,
    group: "additional",
  },
  {
    id: "param-warranty",
    code: "warranty",
    name: "Гарантия",
    type: "select",
    options: [
      { value: "6-months", label: "6 месяцев" },
      { value: "1-year", label: "1 год" },
      { value: "2-years", label: "2 года" },
      { value: "3-years", label: "3 года" },
      { value: "5-years", label: "5 лет" },
    ],
    required: false,
    filterable: false,
    comparable: true,
    showInCard: true,
    showInList: false,
    order: 2,
    group: "additional",
  },
  {
    id: "param-room",
    code: "room",
    name: "Комната",
    type: "multiselect",
    options: [
      { value: "kitchen", label: "Кухня" },
      { value: "living-room", label: "Гостиная" },
      { value: "bedroom", label: "Спальня" },
      { value: "kids-room", label: "Детская" },
      { value: "office", label: "Кабинет" },
      { value: "hallway", label: "Прихожая" },
      { value: "balcony", label: "Балкон" },
      { value: "outdoor", label: "Улица/Сад" },
    ],
    required: false,
    filterable: true,
    comparable: false,
    showInCard: true,
    showInList: false,
    order: 3,
    group: "additional",
  },
  {
    id: "param-purpose",
    code: "purpose",
    name: "Назначение",
    type: "multiselect",
    options: [
      { value: "home", label: "Для дома" },
      { value: "office", label: "Для офиса" },
      { value: "horeca", label: "HoReCa" },
      { value: "outdoor", label: "Для улицы" },
      { value: "kids", label: "Для детей" },
    ],
    required: false,
    filterable: true,
    comparable: false,
    showInCard: true,
    showInList: false,
    order: 4,
    group: "additional",
  },
  {
    id: "param-single-box",
    code: "singleBox",
    name: "В одной коробке",
    type: "boolean",
    required: false,
    filterable: false,
    comparable: false,
    showInCard: false,
    showInList: false,
    order: 5,
    group: "additional",
    avitoField: "Поместится ли товар в одну коробку?",
  },
];

// Функция получения параметров по категории
export function getParametersForCategory(
  categoryCode: string
): ProductParameter[] {
  // Логика выбора параметров по категории
  const categoryParameterMap: Record<string, string[]> = {
    chairs: [
      "chairType",
      "productType",
      "construction",
      "quantity",
      "maxLoad",
      "width",
      "height",
      "depth",
      "seatHeight",
      "weight",
      "frameMaterial",
      "seatMaterial",
      "color",
      "manufacturerColor",
      "frameColor",
      "style",
      "hasArmrests",
      "isFoldable",
      "isRotatable",
      "features",
      "assembly",
      "warranty",
      "room",
      "purpose",
    ],
    tables: [
      "productType",
      "construction",
      "maxLoad",
      "width",
      "height",
      "depth",
      "weight",
      "frameMaterial",
      "tabletopMaterial",
      "color",
      "frameColor",
      "style",
      "assembly",
      "warranty",
      "room",
      "purpose",
    ],
    armchairs: [
      "productType",
      "construction",
      "maxLoad",
      "width",
      "height",
      "depth",
      "seatHeight",
      "weight",
      "frameMaterial",
      "seatMaterial",
      "color",
      "frameColor",
      "style",
      "hasArmrests",
      "hasHeadrest",
      "isRotatable",
      "heightAdjustable",
      "backAdjustable",
      "hasWheels",
      "features",
      "assembly",
      "warranty",
      "room",
      "purpose",
    ],
  };

  const paramCodes = categoryParameterMap[categoryCode] || [];

  return DEFAULT_PARAMETERS.filter((p) => paramCodes.includes(p.code));
}

// Функция группировки параметров
export function groupParameters(
  parameters: ProductParameter[]
): Map<string, ProductParameter[]> {
  const groups = new Map<string, ProductParameter[]>();

  for (const param of parameters) {
    const groupId = param.group || "additional";
    if (!groups.has(groupId)) {
      groups.set(groupId, []);
    }
    groups.get(groupId)!.push(param);
  }

  // Сортируем внутри групп
  for (const [, params] of groups) {
    params.sort((a, b) => a.order - b.order);
  }

  return groups;
}
