server {
    listen 80;
    server_name kupitstul.ru www.kupitstul.ru;

    # Rate limit zone
    limit_req_zone $binary_remote_addr zone=order:10m rate=2r/s;

    include /etc/nginx/conf.d/default.conf;
}
